language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t tscotto5/react-test -f ./client/Dockerfile.dev ./client

scripts:
        - docker run tscotto5/react-test npm test -- --coverage

after_success:
        - docker build -t tscotto5/multi-client ./client
        - docker build -t tscotto5/multi-nginx ./nginx
        - docker build -t tscotto5/multi-server ./server
        - docker build -t tscotto5/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        # Take those images and push them docker hub
        - docker push tscotto5/multi-client
        - docker push tscotto5/multi-nginx
        - docker push tscotto5/multi-server
        - docker push tscotto5/multi-worker
deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-350670948127
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECREY_KEY
